import React, { Component } from 'react'

export class Dashboard extends Component {
	render() {
		return (
			<div>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
				<p>Dashboard</p>
			</div>
		)
	}
}

export default Dashboard
